In [ ]:
#b. Создать массив из 10 нулей
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
a = np.array([0,0,0,0,0,0,0,0,0,0])
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#c создать массив из 10 единиц
import numpy as np1
b = np1.ones(10)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np1
b = np1.array([1,1,1,1,1,1,1,1,1,1])
print(b)

[1 1 1 1 1 1 1 1 1 1]


In [ ]:
#d создать массив из 10 пятерок
import numpy as np
c = np.array([5,5,5,5,5,5,5,5,5,5])
print(c)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
import numpy as np1
c = np1.ones(10)*5
print(c)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e. создать массив из целых чисел от 10 до 50
import numpy as np
ar=np.arange(10,50)
print(ar) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#f. создать массив из четных чисел от 10 до 50
import numpy as np
ar1=np.arange(10,50,2)
print("Массив четных чисел от 10 до 50")
print(ar1) 

Массив четных чисел от 10 до 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [1]:
#g создать матрицу 3*3 с числами от 0 до 8
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
import numpy as np
b = np.arange(9)
c = np.reshape(b, (3, 3))
print("Матрица 3*3 с числами от 0 до 8: \n", c)


Матрица 3*3 с числами от 0 до 8: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
#h создать единичную матрицу 3*3
import numpy as np1
b = np1.ones((3, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
#i Используйте NumPy для генерации случайного числа от 0 до 1
import numpy as np
x = np.random.normal(0,1,1)
print("Случайное число от 0 до 1:")
print(x)

Случайное число от 0 до 1:
[-0.63350853]


In [11]:
#j. Используйте NumPy для генерации массива из 25 случайных чисел,
#взятых из стандартного нормального распределения
import numpy as np
s = np.random.standard_normal(25)
print(s)

[-0.45789237  0.18941957 -1.12853557 -1.45379404  2.48178515 -1.60362256
  0.50247541 -0.11976837 -0.43251805 -0.1736008  -0.15797686  1.45617542
  0.71205048 -0.1267356   1.00599539 -0.10815624  1.28857533  0.57045045
  0.53640411  0.80813842  1.4742563  -0.38416966 -1.30025713 -0.68397503
 -0.35670162]


In [1]:
#k. Создайте матрицу 10*10 от 0 до 1 используя функции библиотеки NumPy
import numpy as np
b = np.arange(0.01, 1.01, 0.01)
c = np.reshape(b, (10, 10))
print(c)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [4]:
import numpy as np
b = np.arange(0.01, 1.01, 0.01).reshape((10, 10))
print(b)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [5]:
#l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!). Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
print(mat[2:, 1:],"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]] 



In [12]:
#m. Написать код обращения к элементу который вернет значение 20 из стартовой матрицы задачи l
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
print(mat[3][4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

20


In [13]:
#n. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#   ([ 2],
#    [ 7],
#    [12]])
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
print(mat[:3,1:2],"\n")


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[ 2]
 [ 7]
 [12]] 



In [14]:
#o. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#   ([21, 22, 23, 24, 25])
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
print(mat[4],"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[21 22 23 24 25] 



In [15]:
#p. Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
#   ([[16, 17, 18, 19, 20],
#     [21, 22, 23, 24, 25]])
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
print(mat[3:],"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[16 17 18 19 20]
 [21 22 23 24 25]] 



In [16]:
#q. Получить сумму всех значений в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
a = mat.sum()
print(a,"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

325 



In [17]:
#r. Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5).std()
print(mat,"\n")

7.211102550927978 



In [18]:
#s. Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print(mat,"\n")
a = mat.sum(axis = 0)
print(a,"\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[55 60 65 70 75] 

